name: Publish release

on:
  release:
    types:
      - published

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Upload binaries
      uses: svenstaro/upload-release-action@2.3.0
      with:
        file: '*.tar.gz'
        file_glob: true
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
